# Generated by Django 3.1.3 on 2020-11-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tlg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
