# Generated by Django 3.1.3 on 2020-11-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tlg', '0005_bottoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TlgBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Логин')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID бота в телеграме')),
                ('token', models.TextField(verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Телеграм бот',
                'verbose_name_plural': 'Телеграм боты',
            },
        ),
        migrations.DeleteModel(
            name='BotToken',
        ),
    ]
