# Generated by Django 3.1.3 on 2020-11-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_tlg', '0006_auto_20201126_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlgbot',
            name='state',
            field=models.TextField(default='off', verbose_name='Состояние'),
        ),
    ]
